/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.cex.ignite.model;

import java.io.*;

/**
 * Transaction definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 02/01/2016.
 */
public class Transaction implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for transactionId. */
    private String transactionId;

    /** Value for cardNo. */
    private String cardNo;

    /** Value for channelId. */
    private String channelId;

    /** Value for upc. */
    private String upc;

    /** Value for loadValue. */
    private double loadValue;

    /** Value for cardStatus. */
    private String cardStatus;

    /** Value for transactionTime. */
    private java.sql.Timestamp transactionTime;

    /** Value for remark. */
    private String remark;

    /**
     * Empty constructor.
     */
    public Transaction() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public Transaction(
        String transactionId,
        String cardNo,
        String channelId,
        String upc,
        double loadValue,
        String cardStatus,
        java.sql.Timestamp transactionTime,
        String remark
    ) {
        this.transactionId = transactionId;
        this.cardNo = cardNo;
        this.channelId = channelId;
        this.upc = upc;
        this.loadValue = loadValue;
        this.cardStatus = cardStatus;
        this.transactionTime = transactionTime;
        this.remark = remark;
    }

    /**
     * Gets transactionId.
     *
     * @return Value for transactionId.
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets transactionId.
     *
     * @param transactionId New value for transactionId.
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * Gets cardNo.
     *
     * @return Value for cardNo.
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * Sets cardNo.
     *
     * @param cardNo New value for cardNo.
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * Gets channelId.
     *
     * @return Value for channelId.
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * Sets channelId.
     *
     * @param channelId New value for channelId.
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    /**
     * Gets upc.
     *
     * @return Value for upc.
     */
    public String getUpc() {
        return upc;
    }

    /**
     * Sets upc.
     *
     * @param upc New value for upc.
     */
    public void setUpc(String upc) {
        this.upc = upc;
    }

    /**
     * Gets loadValue.
     *
     * @return Value for loadValue.
     */
    public double getLoadValue() {
        return loadValue;
    }

    /**
     * Sets loadValue.
     *
     * @param loadValue New value for loadValue.
     */
    public void setLoadValue(double loadValue) {
        this.loadValue = loadValue;
    }

    /**
     * Gets cardStatus.
     *
     * @return Value for cardStatus.
     */
    public String getCardStatus() {
        return cardStatus;
    }

    /**
     * Sets cardStatus.
     *
     * @param cardStatus New value for cardStatus.
     */
    public void setCardStatus(String cardStatus) {
        this.cardStatus = cardStatus;
    }

    /**
     * Gets transactionTime.
     *
     * @return Value for transactionTime.
     */
    public java.sql.Timestamp getTransactionTime() {
        return transactionTime;
    }

    /**
     * Sets transactionTime.
     *
     * @param transactionTime New value for transactionTime.
     */
    public void setTransactionTime(java.sql.Timestamp transactionTime) {
        this.transactionTime = transactionTime;
    }

    /**
     * Gets remark.
     *
     * @return Value for remark.
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Sets remark.
     *
     * @param remark New value for remark.
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof Transaction))
            return false;

        Transaction that = (Transaction)o;

        if (transactionId != null ? !transactionId.equals(that.transactionId) : that.transactionId != null)
            return false;

        if (cardNo != null ? !cardNo.equals(that.cardNo) : that.cardNo != null)
            return false;

        if (channelId != null ? !channelId.equals(that.channelId) : that.channelId != null)
            return false;

        if (upc != null ? !upc.equals(that.upc) : that.upc != null)
            return false;

        if (Double.compare(loadValue, that.loadValue) != 0)
            return false;

        if (cardStatus != null ? !cardStatus.equals(that.cardStatus) : that.cardStatus != null)
            return false;

        if (transactionTime != null ? !transactionTime.equals(that.transactionTime) : that.transactionTime != null)
            return false;

        if (remark != null ? !remark.equals(that.remark) : that.remark != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = transactionId != null ? transactionId.hashCode() : 0;

        res = 31 * res + (cardNo != null ? cardNo.hashCode() : 0);

        res = 31 * res + (channelId != null ? channelId.hashCode() : 0);

        res = 31 * res + (upc != null ? upc.hashCode() : 0);

        long ig_hash_temp = Double.doubleToLongBits(loadValue);

        res = 31 * res + (int)(ig_hash_temp ^ (ig_hash_temp >>> 32));

        res = 31 * res + (cardStatus != null ? cardStatus.hashCode() : 0);

        res = 31 * res + (transactionTime != null ? transactionTime.hashCode() : 0);

        res = 31 * res + (remark != null ? remark.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "Transaction [transactionId=" + transactionId +
            ", cardNo=" + cardNo +
            ", channelId=" + channelId +
            ", upc=" + upc +
            ", loadValue=" + loadValue +
            ", cardStatus=" + cardStatus +
            ", transactionTime=" + transactionTime +
            ", remark=" + remark +
            "]";
    }
}

